/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ModalImport } from './routes/_modal'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as ModalTeamImport } from './routes/_modal.team'
import { Route as ModalContactsImport } from './routes/_modal.contacts'
import { Route as LayoutHomeImport } from './routes/_layout.home'
import { Route as LayoutAboutImport } from './routes/_layout.about'
import { Route as ModalContactsIndexImport } from './routes/_modal.contacts.index'
import { Route as ModalContactsIdImport } from './routes/_modal.contacts.$id'

// Create/Update Routes

const ModalRoute = ModalImport.update({
  id: '/_modal',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ModalTeamRoute = ModalTeamImport.update({
  path: '/team',
  getParentRoute: () => ModalRoute,
} as any)

const ModalContactsRoute = ModalContactsImport.update({
  path: '/contacts',
  getParentRoute: () => ModalRoute,
} as any)

const LayoutHomeRoute = LayoutHomeImport.update({
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const ModalContactsIndexRoute = ModalContactsIndexImport.update({
  path: '/',
  getParentRoute: () => ModalContactsRoute,
} as any)

const ModalContactsIdRoute = ModalContactsIdImport.update({
  path: '/$id',
  getParentRoute: () => ModalContactsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_modal': {
      preLoaderRoute: typeof ModalImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home': {
      preLoaderRoute: typeof LayoutHomeImport
      parentRoute: typeof LayoutImport
    }
    '/_modal/contacts': {
      preLoaderRoute: typeof ModalContactsImport
      parentRoute: typeof ModalImport
    }
    '/_modal/team': {
      preLoaderRoute: typeof ModalTeamImport
      parentRoute: typeof ModalImport
    }
    '/_modal/contacts/$id': {
      preLoaderRoute: typeof ModalContactsIdImport
      parentRoute: typeof ModalContactsImport
    }
    '/_modal/contacts/': {
      preLoaderRoute: typeof ModalContactsIndexImport
      parentRoute: typeof ModalContactsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([LayoutAboutRoute, LayoutHomeRoute]),
  ModalRoute.addChildren([
    ModalContactsRoute.addChildren([
      ModalContactsIdRoute,
      ModalContactsIndexRoute,
    ]),
    ModalTeamRoute,
  ]),
])

/* prettier-ignore-end */
