/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ModalImport } from './routes/modal'
import { Route as MainImport } from './routes/main'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as ModalIndexImport } from './routes/modal/index'
import { Route as MainIndexImport } from './routes/main/index'
import { Route as ModalTeamsImport } from './routes/modal/teams'
import { Route as MainAboutImport } from './routes/main/about'
import { Route as MainAboutIndexImport } from './routes/main/about/index'
import { Route as MainAboutAboutIdImport } from './routes/main/about/$aboutId'

// Create/Update Routes

const ModalRoute = ModalImport.update({
  path: '/modal',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  path: '/main',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ModalIndexRoute = ModalIndexImport.update({
  path: '/',
  getParentRoute: () => ModalRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const ModalTeamsRoute = ModalTeamsImport.update({
  path: '/teams',
  getParentRoute: () => ModalRoute,
} as any)

const MainAboutRoute = MainAboutImport.update({
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)

const MainAboutIndexRoute = MainAboutIndexImport.update({
  path: '/',
  getParentRoute: () => MainAboutRoute,
} as any)

const MainAboutAboutIdRoute = MainAboutAboutIdImport.update({
  path: '/$aboutId',
  getParentRoute: () => MainAboutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/modal': {
      preLoaderRoute: typeof ModalImport
      parentRoute: typeof rootRoute
    }
    '/main/about': {
      preLoaderRoute: typeof MainAboutImport
      parentRoute: typeof MainImport
    }
    '/modal/teams': {
      preLoaderRoute: typeof ModalTeamsImport
      parentRoute: typeof ModalImport
    }
    '/main/': {
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/modal/': {
      preLoaderRoute: typeof ModalIndexImport
      parentRoute: typeof ModalImport
    }
    '/main/about/$aboutId': {
      preLoaderRoute: typeof MainAboutAboutIdImport
      parentRoute: typeof MainAboutImport
    }
    '/main/about/': {
      preLoaderRoute: typeof MainAboutIndexImport
      parentRoute: typeof MainAboutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute,
  MainRoute.addChildren([
    MainAboutRoute.addChildren([MainAboutAboutIdRoute, MainAboutIndexRoute]),
    MainIndexRoute,
  ]),
  ModalRoute.addChildren([ModalTeamsRoute, ModalIndexRoute]),
])

/* prettier-ignore-end */
